<a href="https://colab.research.google.com/github/daniel27a/missp/blob/main/cd_podstaw_pythona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
print(a_list+b_list)
print(n_array+n_array)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
a_list[3]

4

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
k_krotka[6]

'temat'

In [ ]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
print(np.array(b_list)+np.array(b_list))

[ 2  4  6  8 10]


In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: [1,2,3],"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [ ]:
del studenci_slownik["Frankek"]
studenci_slownik.items()

dict_items([(123, [1, 2, 3]), ('Igor', 3), ('Zosia', 22), ('Julia', [2, 21]), ((1, 2), 'Krotka'), ('nowe', [88])])

In [ ]:
studenci_slownik[1]

NameError: ignored

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Zosia
Julia
(1, 2)
nowe
********************
123
Igor
Zosia
Julia
(1, 2)
nowe


In [ ]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [ ]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%3==0]
print(automatyczna_lista)

[0, 9, 36, 81, 144, 225, 324, 441, 576, 729, 900, 1089, 1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356, 4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,5,"Franek"}


In [ ]:
a&b #suma zbiorów, sum of sets

{2, 3, 'Franek'}

In [ ]:
del a ("Fran")
print(a)

SyntaxError: ignored

In [ ]:
45 in a
"Igo5r" in studenci_slownik

False

### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

SyntaxError: ignored

In [227]:


class NumerTelefonu:

    def __init__(self, sprawdz_numer):
        self.numer = sprawdz_numer
        print("wprowadzono numer:")
        print(self.numer)
      
    @property
    def check_poprawnosc(self):
        if (len(self.numer)==9):
          print("wprowadzono poprawny numer")     
        else:
          print("ERROR: wprowadzono numer o zlej dlugosci")

    @property
    def check_voivod(self):
      print("Wojewodztwo:")
      numb0 = int(self.numer[0])
      numb1 = int(self.numer[1])
      prefix = numb0*10 + numb1  
      if (prefix==46):
        print("Warszawa")
      elif (prefix==22):
        print("Łódź") 
      else:
        print("nieznane wojewodztwo")
    
    @property
    def wypisz(self):
      numer_slownie = ""
      cyfry_slownie = ["zero", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewieć"]
      for i in range(len(self.numer)):
        numer_slownie += cyfry_slownie[int(self.numer[i])] + " "
      print (numer_slownie)  


   
sprawdz_numer = NumerTelefonu("222234567")
sprawdz_numer.check_poprawnosc
sprawdz_numer.check_voivod
sprawdz_numer.wypisz








    
    




wprowadzono numer:
222234567
wprowadzono poprawny numer
Wojewodztwo:
Łódź
dwa dwa dwa dwa trzy cztery pięć sześć siedem 
