<a href="https://colab.research.google.com/github/daniel27a/missp/blob/main/podstawy/cd_podstaw_pythona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wykonał
## Daniel Sobczak
### 215342

>W poniższy Notebooku zostały przedstawione bardziej zaawansowane funkcje języka Python. W trakcie wykonywania ćwiczeń zapoznałem się z obsługą list, krotek, słowników, macierzy. Nauczyłem się dodawać listy do siebie oraz pojedyncze elementy do tych list. Opanowałem tworzenie i edytowanie słowników.





In [1]:
import numpy as np

In [2]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [3]:
print(a_list+b_list)
print(n_array+n_array)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [4]:
a_list[3]

4

In [5]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [6]:
k_krotka[6]

'temat'

In [8]:
print(np.array(b_list)+np.array(b_list))

[ 2  4  6  8 10]


In [9]:
n_array = np.array(a_list) # wektor numpy

In [10]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [11]:
#### Nowosci

studenci_slownik = {123: [1,2,3],"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [12]:
del studenci_slownik["Frankek"]
studenci_slownik.items()

dict_items([(123, [1, 2, 3]), ('Igor', 3), ('Zosia', 22), ('Julia', [2, 21]), ((1, 2), 'Krotka')])

In [16]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Zosia
Julia
(1, 2)
********************
123
Igor
Zosia
Julia
(1, 2)


In [17]:
for elementy in studenci_slownik.items():
    print(elementy)

(123, [1, 2, 3])
('Igor', 3)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [18]:
for elementy in studenci_slownik.values():
    print(elementy)

[1, 2, 3]
3
22
[2, 21]
Krotka


In [19]:
studenci_slownik["Cuthulu"]= -1000000

In [20]:
studenci_slownik

{(1, 2): 'Krotka',
 123: [1, 2, 3],
 'Cuthulu': -1000000,
 'Igor': 3,
 'Julia': [2, 21],
 'Zosia': 22}

In [21]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%3==0]
print(automatyczna_lista)

[0, 9, 36, 81, 144, 225, 324, 441, 576, 729, 900, 1089, 1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356, 4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801]


In [22]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Zosia', 3: 'Julia', 4: (1, 2), 5: 'Cuthulu'}


In [55]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,5,"Franek"}


In [24]:
a&b #suma zbiorów, sum of sets

{2, 3, 'Franek'}

In [31]:
45 in a
"Igo5r" in studenci_slownik

False

### Własne typy
>W dalszej części ćwiczenia zapoznałem się z klasami i definicjami. Służyły one do obsługi list, dodawania do nich elementów, sortowania i wyświetlania.


In [36]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [58]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [59]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [60]:
pio_zajecia.ile_zajec

4

In [61]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [62]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [44]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [45]:
pio_zajecia.ile_mispow()

4

In [46]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [47]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [48]:
print(pio_zajecia.ile_zajec)

5


In [49]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [50]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [51]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [52]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [54]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. że to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

Poniżej przedstawiłem rozwiązanie postawionego przede mną challange'u. 

Stworzony przeze mnie program służy do rozpoznawania pewnych właściwości wpisywanego przez użytkownika numeru. 
Pierwszą ze sprawdzanych właściwości jest jego długość. Wpisywany numer musi mieć długość 9 znaków. W przypadku wpisania numeru o złej długości zostanie wyświetlony odpowiedni komunikat. 

In [67]:
print ("Podaj dziewięcio cyfrowy numer telefonu!")
wprowadzony_numer = input()

class NumerTelefonu:

    def __init__(self, sprawdz_numer):
        self.numer = sprawdz_numer
        print("Wprowadzono numer:", self.numer,)
      
    @property
    def check_poprawnosc(self):
        if (len(self.numer)==9):
          print("Wprowadzono poprawny numer!")     
        else:
          print("ERROR: wprowadzono numer o złej długosci!")

    @property
    def check_voivod(self):
      kierunkowe_Łódzkie = [42, 43, 44]
      kierunkowe_Mazowieckie = [22, 23, 24]
      voivod = ""
      prefix = int(self.numer[0])*10 + int(self.numer[1])
      if (prefix in kierunkowe_Mazowieckie):
        voivod = "Mazowieckie"
      elif (prefix in kierunkowe_Łódzkie):
        voivod = "Łódzkie" 
      else:
        voivod = "Nieznane"
      print("Województwo:", voivod)

    @property
    def wypisz(self):
      numer_slownie = ""
      cyfry_slownie = ["zero", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewieć"]
      for i in range(len(self.numer)):
        numer_slownie += cyfry_slownie[int(self.numer[i])] + " "
      print ("Numer słownie:", numer_slownie)  


   
sprawdz_numer = NumerTelefonu(wprowadzony_numer)
sprawdz_numer.check_poprawnosc
sprawdz_numer.check_voivod
sprawdz_numer.wypisz

Podaj dziewięcio cyfrowy numer telefonu!


KeyboardInterrupt: ignored